name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pre-commit pytest

      - name: Run pre-commit
        id: precommit
        run: |
          set +e
          pre-commit run --all-files --show-diff-on-failure
          status=$?
          if [ -n "$(git status --porcelain)" ]; then
            echo "formatting_changed=true" >> "$GITHUB_OUTPUT"
            status=0
          fi
          exit $status

      - name: Commit formatting changes
        if: steps.precommit.outputs.formatting_changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "chore: apply ruff formatting"
          git push

      - name: Re-run pre-commit
        if: steps.precommit.outputs.formatting_changed == 'true'
        run: pre-commit run --all-files --show-diff-on-failure
